/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TournamentType = IDL.Variant({
  'battleground' : IDL.Null,
  'custom4v4' : IDL.Null,
});
export const Time = IDL.Int;
export const NotificationType = IDL.Variant({
  'prizeCredited' : IDL.Null,
  'scoresUpdated' : IDL.Null,
  'tournamentStarting' : IDL.Null,
  'registrationConfirmed' : IDL.Null,
});
export const NotificationRecord = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'notificationType' : NotificationType,
  'read' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
  'bonus' : IDL.Null,
  'entryFee' : IDL.Null,
  'prize' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'role' : IDL.Variant({ 'admin' : IDL.Null, 'player' : IDL.Null }),
  'banned' : IDL.Bool,
  'email' : IDL.Text,
});
export const DepositRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const RegistrationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const TeamRegistration = IDL.Record({
  'id' : IDL.Nat,
  'status' : RegistrationStatus,
  'teamId' : IDL.Nat,
  'tournamentId' : IDL.Nat,
  'captainId' : IDL.Principal,
});
export const Wallet = IDL.Record({
  'balance' : IDL.Nat,
  'transactions' : IDL.Vec(Transaction),
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'placementRank' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'teamId' : IDL.Nat,
  'kills' : IDL.Nat,
});
export const PrizeDistribution = IDL.Record({
  'firstPlace' : IDL.Nat,
  'thirdPlace' : IDL.Nat,
  'mostKills' : IDL.Nat,
  'secondPlace' : IDL.Nat,
  'remaining' : IDL.Nat,
  'tournamentId' : IDL.Nat,
  'highKills' : IDL.Nat,
});
export const Player = IDL.Record({
  'freeFireId' : IDL.Text,
  'name' : IDL.Text,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'members' : IDL.Vec(Player),
  'substitutes' : IDL.Opt(IDL.Vec(Player)),
  'name' : IDL.Text,
  'captain' : IDL.Principal,
});
export const TournamentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'status' : TournamentStatus,
  'tournamentType' : TournamentType,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'roomPassword' : IDL.Opt(IDL.Text),
  'maxTeams' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'roomId' : IDL.Opt(IDL.Text),
  'prizePool' : IDL.Nat,
});
export const TournamentScore = IDL.Record({
  'id' : IDL.Nat,
  'placementRank' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'kills' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustUserBalance' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'approveDeposit' : IDL.Func([IDL.Nat], [], []),
  'approveTeamRegistration' : IDL.Func([IDL.Nat], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'createTournament' : IDL.Func(
      [IDL.Text, TournamentType, IDL.Nat, IDL.Nat, Time],
      [IDL.Nat],
      [],
    ),
  'distributePrizes' : IDL.Func([IDL.Nat], [], []),
  'getAllNotifications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(NotificationRecord)))],
      ['query'],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(DepositRequest)],
      ['query'],
    ),
  'getCallerNotifications' : IDL.Func(
      [],
      [IDL.Vec(NotificationRecord)],
      ['query'],
    ),
  'getCallerStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalWinnings' : IDL.Nat,
          'tournamentsParticipated' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerTeamRegistrations' : IDL.Func(
      [],
      [IDL.Vec(TeamRegistration)],
      ['query'],
    ),
  'getCallerTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
  'getCallerWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getFutureTournamentStartTimes' : IDL.Func([], [IDL.Vec(Time)], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalPrizeDistributed' : IDL.Nat,
          'totalPlayers' : IDL.Nat,
          'totalTournaments' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPrizeDistributions' : IDL.Func(
      [],
      [IDL.Vec(PrizeDistribution)],
      ['query'],
    ),
  'getRegistrationsByTournament' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TeamRegistration)],
      ['query'],
    ),
  'getTeamRegistrations' : IDL.Func([], [IDL.Vec(TeamRegistration)], ['query']),
  'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getTournamentById' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournamentScores' : IDL.Func([], [IDL.Vec(TournamentScore)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getTransactionsByType' : IDL.Func(
      [TransactionType],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByUserId' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserBalances' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'totalWinnings' : IDL.Nat,
          'tournamentsParticipated' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getWalletByUserId' : IDL.Func([IDL.Principal], [IDL.Opt(Wallet)], ['query']),
  'getWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
  'getWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'registerTeam' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(Player), IDL.Opt(IDL.Vec(Player))],
      [IDL.Nat],
      [],
    ),
  'rejectDeposit' : IDL.Func([IDL.Nat], [], []),
  'rejectTeamRegistration' : IDL.Func([IDL.Nat], [], []),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'updateTeamScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateTournamentRoomCredentials' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTournamentStatus' : IDL.Func([IDL.Nat, TournamentStatus], [], []),
  'userDeposit' : IDL.Func([IDL.Nat], [DepositRequest], []),
  'userWithdraw' : IDL.Func([IDL.Nat], [WithdrawalRequest], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TournamentType = IDL.Variant({
    'battleground' : IDL.Null,
    'custom4v4' : IDL.Null,
  });
  const Time = IDL.Int;
  const NotificationType = IDL.Variant({
    'prizeCredited' : IDL.Null,
    'scoresUpdated' : IDL.Null,
    'tournamentStarting' : IDL.Null,
    'registrationConfirmed' : IDL.Null,
  });
  const NotificationRecord = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'notificationType' : NotificationType,
    'read' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'bonus' : IDL.Null,
    'entryFee' : IDL.Null,
    'prize' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'role' : IDL.Variant({ 'admin' : IDL.Null, 'player' : IDL.Null }),
    'banned' : IDL.Bool,
    'email' : IDL.Text,
  });
  const DepositRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const RegistrationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const TeamRegistration = IDL.Record({
    'id' : IDL.Nat,
    'status' : RegistrationStatus,
    'teamId' : IDL.Nat,
    'tournamentId' : IDL.Nat,
    'captainId' : IDL.Principal,
  });
  const Wallet = IDL.Record({
    'balance' : IDL.Nat,
    'transactions' : IDL.Vec(Transaction),
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'placementRank' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'teamId' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  const PrizeDistribution = IDL.Record({
    'firstPlace' : IDL.Nat,
    'thirdPlace' : IDL.Nat,
    'mostKills' : IDL.Nat,
    'secondPlace' : IDL.Nat,
    'remaining' : IDL.Nat,
    'tournamentId' : IDL.Nat,
    'highKills' : IDL.Nat,
  });
  const Player = IDL.Record({ 'freeFireId' : IDL.Text, 'name' : IDL.Text });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'members' : IDL.Vec(Player),
    'substitutes' : IDL.Opt(IDL.Vec(Player)),
    'name' : IDL.Text,
    'captain' : IDL.Principal,
  });
  const TournamentStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'status' : TournamentStatus,
    'tournamentType' : TournamentType,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'roomPassword' : IDL.Opt(IDL.Text),
    'maxTeams' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'roomId' : IDL.Opt(IDL.Text),
    'prizePool' : IDL.Nat,
  });
  const TournamentScore = IDL.Record({
    'id' : IDL.Nat,
    'placementRank' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustUserBalance' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'approveDeposit' : IDL.Func([IDL.Nat], [], []),
    'approveTeamRegistration' : IDL.Func([IDL.Nat], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'createTournament' : IDL.Func(
        [IDL.Text, TournamentType, IDL.Nat, IDL.Nat, Time],
        [IDL.Nat],
        [],
      ),
    'distributePrizes' : IDL.Func([IDL.Nat], [], []),
    'getAllNotifications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(NotificationRecord)))],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getCallerNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationRecord)],
        ['query'],
      ),
    'getCallerStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalWinnings' : IDL.Nat,
            'tournamentsParticipated' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerTeamRegistrations' : IDL.Func(
        [],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'getCallerTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'getCallerWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getFutureTournamentStartTimes' : IDL.Func([], [IDL.Vec(Time)], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPrizeDistributed' : IDL.Nat,
            'totalPlayers' : IDL.Nat,
            'totalTournaments' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPrizeDistributions' : IDL.Func(
        [],
        [IDL.Vec(PrizeDistribution)],
        ['query'],
      ),
    'getRegistrationsByTournament' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'getTeamRegistrations' : IDL.Func(
        [],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getTournamentById' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournamentScores' : IDL.Func([], [IDL.Vec(TournamentScore)], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getTransactionsByType' : IDL.Func(
        [TransactionType],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserBalances' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'totalWinnings' : IDL.Nat,
            'tournamentsParticipated' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getWalletByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Wallet)],
        ['query'],
      ),
    'getWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
    'getWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'registerTeam' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(Player), IDL.Opt(IDL.Vec(Player))],
        [IDL.Nat],
        [],
      ),
    'rejectDeposit' : IDL.Func([IDL.Nat], [], []),
    'rejectTeamRegistration' : IDL.Func([IDL.Nat], [], []),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'updateTeamScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateTournamentRoomCredentials' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTournamentStatus' : IDL.Func([IDL.Nat, TournamentStatus], [], []),
    'userDeposit' : IDL.Func([IDL.Nat], [DepositRequest], []),
    'userWithdraw' : IDL.Func([IDL.Nat], [WithdrawalRequest], []),
  });
};

export const init = ({ IDL }) => { return []; };