/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DepositRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userId' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface LeaderboardEntry {
  'placementRank' : bigint,
  'totalPoints' : bigint,
  'teamId' : bigint,
  'kills' : bigint,
}
export interface NotificationRecord {
  'id' : bigint,
  'userId' : Principal,
  'notificationType' : NotificationType,
  'read' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export type NotificationType = { 'prizeCredited' : null } |
  { 'scoresUpdated' : null } |
  { 'tournamentStarting' : null } |
  { 'registrationConfirmed' : null };
export interface Player { 'freeFireId' : string, 'name' : string }
export interface PrizeDistribution {
  'firstPlace' : bigint,
  'thirdPlace' : bigint,
  'mostKills' : bigint,
  'secondPlace' : bigint,
  'remaining' : bigint,
  'tournamentId' : bigint,
  'highKills' : bigint,
}
export type RegistrationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Team {
  'id' : bigint,
  'members' : Array<Player>,
  'substitutes' : [] | [Array<Player>],
  'name' : string,
  'captain' : Principal,
}
export interface TeamRegistration {
  'id' : bigint,
  'status' : RegistrationStatus,
  'teamId' : bigint,
  'tournamentId' : bigint,
  'captainId' : Principal,
}
export type Time = bigint;
export interface Tournament {
  'id' : bigint,
  'startTime' : Time,
  'status' : TournamentStatus,
  'tournamentType' : TournamentType,
  'name' : string,
  'createdBy' : Principal,
  'roomPassword' : [] | [string],
  'maxTeams' : bigint,
  'entryFee' : bigint,
  'roomId' : [] | [string],
  'prizePool' : bigint,
}
export interface TournamentScore {
  'id' : bigint,
  'placementRank' : bigint,
  'totalPoints' : bigint,
  'kills' : bigint,
}
export type TournamentStatus = { 'upcoming' : null } |
  { 'completed' : null } |
  { 'ongoing' : null };
export type TournamentType = { 'battleground' : null } |
  { 'custom4v4' : null };
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'userId' : Principal,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null } |
  { 'bonus' : null } |
  { 'entryFee' : null } |
  { 'prize' : null };
export interface UserProfile {
  'referralCode' : string,
  'username' : string,
  'role' : { 'admin' : null } |
    { 'player' : null },
  'banned' : boolean,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'balance' : bigint,
  'transactions' : Array<Transaction>,
}
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userId' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adjustUserBalance' : ActorMethod<[Principal, bigint], undefined>,
  'approveDeposit' : ActorMethod<[bigint], undefined>,
  'approveTeamRegistration' : ActorMethod<[bigint], undefined>,
  'approveWithdrawal' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'createTournament' : ActorMethod<
    [string, TournamentType, bigint, bigint, Time],
    bigint
  >,
  'distributePrizes' : ActorMethod<[bigint], undefined>,
  'getAllNotifications' : ActorMethod<
    [],
    Array<[Principal, Array<NotificationRecord>]>
  >,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getCallerNotifications' : ActorMethod<[], Array<NotificationRecord>>,
  'getCallerStats' : ActorMethod<
    [],
    { 'totalWinnings' : bigint, 'tournamentsParticipated' : bigint }
  >,
  'getCallerTeamRegistrations' : ActorMethod<[], Array<TeamRegistration>>,
  'getCallerTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWallet' : ActorMethod<[], [] | [Wallet]>,
  'getCallerWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getFutureTournamentStartTimes' : ActorMethod<[], Array<Time>>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getPlatformStats' : ActorMethod<
    [],
    {
      'totalPrizeDistributed' : bigint,
      'totalPlayers' : bigint,
      'totalTournaments' : bigint,
    }
  >,
  'getPrizeDistributions' : ActorMethod<[], Array<PrizeDistribution>>,
  'getRegistrationsByTournament' : ActorMethod<
    [bigint],
    Array<TeamRegistration>
  >,
  'getTeamRegistrations' : ActorMethod<[], Array<TeamRegistration>>,
  'getTeams' : ActorMethod<[], Array<Team>>,
  'getTournamentById' : ActorMethod<[bigint], [] | [Tournament]>,
  'getTournamentScores' : ActorMethod<[], Array<TournamentScore>>,
  'getTournaments' : ActorMethod<[], Array<Tournament>>,
  'getTransactionsByType' : ActorMethod<[TransactionType], Array<Transaction>>,
  'getTransactionsByUserId' : ActorMethod<[Principal], Array<Transaction>>,
  'getUserBalances' : ActorMethod<[], Array<bigint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<
    [Principal],
    { 'totalWinnings' : bigint, 'tournamentsParticipated' : bigint }
  >,
  'getWalletByUserId' : ActorMethod<[Principal], [] | [Wallet]>,
  'getWallets' : ActorMethod<[], Array<Wallet>>,
  'getWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'registerTeam' : ActorMethod<
    [bigint, string, Array<Player>, [] | [Array<Player>]],
    bigint
  >,
  'rejectDeposit' : ActorMethod<[bigint], undefined>,
  'rejectTeamRegistration' : ActorMethod<[bigint], undefined>,
  'rejectWithdrawal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'updateTeamScore' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
  'updateTournamentRoomCredentials' : ActorMethod<
    [bigint, string, string],
    undefined
  >,
  'updateTournamentStatus' : ActorMethod<[bigint, TournamentStatus], undefined>,
  'userDeposit' : ActorMethod<[bigint], DepositRequest>,
  'userWithdraw' : ActorMethod<[bigint], WithdrawalRequest>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];