/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    freeFireId: string;
    name: string;
}
export interface LeaderboardEntry {
    placementRank: bigint;
    totalPoints: bigint;
    teamId: bigint;
    kills: bigint;
}
export type Time = bigint;
export interface Tournament {
    id: bigint;
    startTime: Time;
    status: TournamentStatus;
    tournamentType: TournamentType;
    name: string;
    createdBy: Principal;
    roomPassword?: string;
    maxTeams: bigint;
    entryFee: bigint;
    roomId?: string;
    prizePool: bigint;
}
export interface TeamRegistration {
    id: bigint;
    status: RegistrationStatus;
    teamId: bigint;
    tournamentId: bigint;
    captainId: Principal;
}
export interface PrizeDistribution {
    firstPlace: bigint;
    thirdPlace: bigint;
    mostKills: bigint;
    secondPlace: bigint;
    remaining: bigint;
    tournamentId: bigint;
    highKills: bigint;
}
export interface Transaction {
    id: bigint;
    transactionType: TransactionType;
    userId: Principal;
    description: string;
    timestamp: Time;
    amount: bigint;
}
export interface Wallet {
    balance: bigint;
    transactions: Array<Transaction>;
}
export interface NotificationRecord {
    id: bigint;
    userId: Principal;
    notificationType: NotificationType;
    read: boolean;
    message: string;
    timestamp: Time;
}
export interface DepositRequest {
    id: bigint;
    status: RegistrationStatus;
    userId: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface WithdrawalRequest {
    id: bigint;
    status: RegistrationStatus;
    userId: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface TournamentScore {
    id: bigint;
    placementRank: bigint;
    totalPoints: bigint;
    kills: bigint;
}
export interface UserProfile {
    referralCode: string;
    username: string;
    role: Variant_admin_player;
    banned: boolean;
    email: string;
}
export interface Team {
    id: bigint;
    members: Array<Player>;
    substitutes?: Array<Player>;
    name: string;
    captain: Principal;
}
export enum NotificationType {
    prizeCredited = "prizeCredited",
    scoresUpdated = "scoresUpdated",
    tournamentStarting = "tournamentStarting",
    registrationConfirmed = "registrationConfirmed"
}
export enum RegistrationStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum TournamentStatus {
    upcoming = "upcoming",
    completed = "completed",
    ongoing = "ongoing"
}
export enum TournamentType {
    battleground = "battleground",
    custom4v4 = "custom4v4"
}
export enum TransactionType {
    deposit = "deposit",
    withdrawal = "withdrawal",
    bonus = "bonus",
    entryFee = "entryFee",
    prize = "prize"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_admin_player {
    admin = "admin",
    player = "player"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adjustUserBalance(userId: Principal, amount: bigint): Promise<void>;
    approveDeposit(depositId: bigint): Promise<void>;
    approveTeamRegistration(registrationId: bigint): Promise<void>;
    approveWithdrawal(withdrawalId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(userId: Principal): Promise<void>;
    createTournament(name: string, tournamentType: TournamentType, entryFee: bigint, maxTeams: bigint, startTime: Time): Promise<bigint>;
    distributePrizes(tournamentId: bigint): Promise<void>;
    getAllNotifications(): Promise<Array<[Principal, Array<NotificationRecord>]>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerDepositRequests(): Promise<Array<DepositRequest>>;
    getCallerNotifications(): Promise<Array<NotificationRecord>>;
    getCallerStats(): Promise<{
        totalWinnings: bigint;
        tournamentsParticipated: bigint;
    }>;
    getCallerTeamRegistrations(): Promise<Array<TeamRegistration>>;
    getCallerTransactions(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWallet(): Promise<Wallet | null>;
    getCallerWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getDepositRequests(): Promise<Array<DepositRequest>>;
    getFutureTournamentStartTimes(): Promise<Array<Time>>;
    getLeaderboard(tournamentId: bigint): Promise<Array<LeaderboardEntry>>;
    getPlatformStats(): Promise<{
        totalPrizeDistributed: bigint;
        totalPlayers: bigint;
        totalTournaments: bigint;
    }>;
    getPrizeDistributions(): Promise<Array<PrizeDistribution>>;
    getRegistrationsByTournament(tournamentId: bigint): Promise<Array<TeamRegistration>>;
    getTeamRegistrations(): Promise<Array<TeamRegistration>>;
    getTeams(): Promise<Array<Team>>;
    getTournamentById(tournamentId: bigint): Promise<Tournament | null>;
    getTournamentScores(): Promise<Array<TournamentScore>>;
    getTournaments(): Promise<Array<Tournament>>;
    getTransactionsByType(transactionType: TransactionType): Promise<Array<Transaction>>;
    getTransactionsByUserId(userId: Principal): Promise<Array<Transaction>>;
    getUserBalances(): Promise<Array<bigint>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStats(userId: Principal): Promise<{
        totalWinnings: bigint;
        tournamentsParticipated: bigint;
    }>;
    getWalletByUserId(userId: Principal): Promise<Wallet | null>;
    getWallets(): Promise<Array<Wallet>>;
    getWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    registerTeam(tournamentId: bigint, teamName: string, members: Array<Player>, substitutes: Array<Player> | null): Promise<bigint>;
    rejectDeposit(depositId: bigint): Promise<void>;
    rejectTeamRegistration(registrationId: bigint): Promise<void>;
    rejectWithdrawal(withdrawalId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unbanUser(userId: Principal): Promise<void>;
    updateTeamScore(tournamentId: bigint, teamId: bigint, kills: bigint, placementRank: bigint): Promise<void>;
    updateTournamentRoomCredentials(tournamentId: bigint, roomId: string, roomPassword: string): Promise<void>;
    updateTournamentStatus(tournamentId: bigint, status: TournamentStatus): Promise<void>;
    userDeposit(amount: bigint): Promise<DepositRequest>;
    userWithdraw(amount: bigint): Promise<WithdrawalRequest>;
}
import type { DepositRequest as _DepositRequest, NotificationRecord as _NotificationRecord, NotificationType as _NotificationType, Player as _Player, RegistrationStatus as _RegistrationStatus, Team as _Team, TeamRegistration as _TeamRegistration, Time as _Time, Tournament as _Tournament, TournamentStatus as _TournamentStatus, TournamentType as _TournamentType, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, Wallet as _Wallet, WithdrawalRequest as _WithdrawalRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adjustUserBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustUserBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustUserBalance(arg0, arg1);
            return result;
        }
    }
    async approveDeposit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDeposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDeposit(arg0);
            return result;
        }
    }
    async approveTeamRegistration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTeamRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTeamRegistration(arg0);
            return result;
        }
    }
    async approveWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: TournamentType, arg2: bigint, arg3: bigint, arg4: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, to_candid_TournamentType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, to_candid_TournamentType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async distributePrizes(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.distributePrizes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.distributePrizes(arg0);
            return result;
        }
    }
    async getAllNotifications(): Promise<Array<[Principal, Array<NotificationRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotifications();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotifications();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDepositRequests();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDepositRequests();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerNotifications(): Promise<Array<NotificationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerNotifications();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerNotifications();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerStats(): Promise<{
        totalWinnings: bigint;
        tournamentsParticipated: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStats();
            return result;
        }
    }
    async getCallerTeamRegistrations(): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTeamRegistrations();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTeamRegistrations();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTransactions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTransactions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWallet(): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWallet();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWallet();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWithdrawalRequests();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWithdrawalRequests();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepositRequests();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepositRequests();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFutureTournamentStartTimes(): Promise<Array<Time>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFutureTournamentStartTimes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFutureTournamentStartTimes();
            return result;
        }
    }
    async getLeaderboard(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return result;
        }
    }
    async getPlatformStats(): Promise<{
        totalPrizeDistributed: bigint;
        totalPlayers: bigint;
        totalTournaments: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getPrizeDistributions(): Promise<Array<PrizeDistribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrizeDistributions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrizeDistributions();
            return result;
        }
    }
    async getRegistrationsByTournament(arg0: bigint): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationsByTournament(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationsByTournament(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamRegistrations(): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamRegistrations();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamRegistrations();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeams();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeams();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentById(arg0: bigint): Promise<Tournament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentById(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentById(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentScores(): Promise<Array<TournamentScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentScores();
            return result;
        }
    }
    async getTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournaments();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournaments();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByType(arg0: TransactionType): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByUserId(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByUserId(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByUserId(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBalances(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBalances();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStats(arg0: Principal): Promise<{
        totalWinnings: bigint;
        tournamentsParticipated: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats(arg0);
            return result;
        }
    }
    async getWalletByUserId(arg0: Principal): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletByUserId(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletByUserId(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallets(): Promise<Array<Wallet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallets();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallets();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequests();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequests();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async registerTeam(arg0: bigint, arg1: string, arg2: Array<Player>, arg3: Array<Player> | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTeam(arg0, arg1, arg2, to_candid_opt_n53(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTeam(arg0, arg1, arg2, to_candid_opt_n53(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async rejectDeposit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDeposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDeposit(arg0);
            return result;
        }
    }
    async rejectTeamRegistration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTeamRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTeamRegistration(arg0);
            return result;
        }
    }
    async rejectWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
    async updateTeamScore(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamScore(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamScore(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTournamentRoomCredentials(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentRoomCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentRoomCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTournamentStatus(arg0: bigint, arg1: TournamentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentStatus(arg0, to_candid_TournamentStatus_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentStatus(arg0, to_candid_TournamentStatus_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async userDeposit(arg0: bigint): Promise<DepositRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.userDeposit(arg0);
                return from_candid_DepositRequest_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.userDeposit(arg0);
            return from_candid_DepositRequest_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async userWithdraw(arg0: bigint): Promise<WithdrawalRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.userWithdraw(arg0);
                return from_candid_WithdrawalRequest_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.userWithdraw(arg0);
            return from_candid_WithdrawalRequest_n36(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DepositRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositRequest): DepositRequest {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationRecord): NotificationRecord {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationStatus): RegistrationStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TeamRegistration_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamRegistration): TeamRegistration {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentType): TournamentType {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Tournament_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tournament): Tournament {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Wallet_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Wallet): Wallet {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Wallet]): Wallet | null {
    return value.length === 0 ? null : from_candid_Wallet_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Player>]): Array<Player> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tournament]): Tournament | null {
    return value.length === 0 ? null : from_candid_Tournament_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: _TransactionType;
    userId: Principal;
    description: string;
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    transactionType: TransactionType;
    userId: Principal;
    description: string;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n15(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    username: string;
    role: {
        admin: null;
    } | {
        player: null;
    };
    banned: boolean;
    email: string;
}): {
    referralCode: string;
    username: string;
    role: Variant_admin_player;
    banned: boolean;
    email: string;
} {
    return {
        referralCode: value.referralCode,
        username: value.username,
        role: from_candid_variant_n20(_uploadFile, _downloadFile, value.role),
        banned: value.banned,
        email: value.email
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    userId: Principal;
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    status: RegistrationStatus;
    userId: Principal;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n24(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RegistrationStatus;
    teamId: bigint;
    tournamentId: bigint;
    captainId: Principal;
}): {
    id: bigint;
    status: RegistrationStatus;
    teamId: bigint;
    tournamentId: bigint;
    captainId: Principal;
} {
    return {
        id: value.id,
        status: from_candid_RegistrationStatus_n28(_uploadFile, _downloadFile, value.status),
        teamId: value.teamId,
        tournamentId: value.tournamentId,
        captainId: value.captainId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: bigint;
    transactions: Array<_Transaction>;
}): {
    balance: bigint;
    transactions: Array<Transaction>;
} {
    return {
        balance: value.balance,
        transactions: from_candid_vec_n12(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    members: Array<_Player>;
    substitutes: [] | [Array<_Player>];
    name: string;
    captain: Principal;
}): {
    id: bigint;
    members: Array<Player>;
    substitutes?: Array<Player>;
    name: string;
    captain: Principal;
} {
    return {
        id: value.id,
        members: value.members,
        substitutes: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.substitutes)),
        name: value.name,
        captain: value.captain
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    status: _TournamentStatus;
    tournamentType: _TournamentType;
    name: string;
    createdBy: Principal;
    roomPassword: [] | [string];
    maxTeams: bigint;
    entryFee: bigint;
    roomId: [] | [string];
    prizePool: bigint;
}): {
    id: bigint;
    startTime: Time;
    status: TournamentStatus;
    tournamentType: TournamentType;
    name: string;
    createdBy: Principal;
    roomPassword?: string;
    maxTeams: bigint;
    entryFee: bigint;
    roomId?: string;
    prizePool: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_TournamentStatus_n44(_uploadFile, _downloadFile, value.status),
        tournamentType: from_candid_TournamentType_n46(_uploadFile, _downloadFile, value.tournamentType),
        name: value.name,
        createdBy: value.createdBy,
        roomPassword: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.roomPassword)),
        maxTeams: value.maxTeams,
        entryFee: value.entryFee,
        roomId: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.roomId)),
        prizePool: value.prizePool
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: Principal;
    notificationType: _NotificationType;
    read: boolean;
    message: string;
    timestamp: _Time;
}): {
    id: bigint;
    userId: Principal;
    notificationType: NotificationType;
    read: boolean;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n10(_uploadFile, _downloadFile, value.notificationType),
        read: value.read,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_NotificationRecord>]): [Principal, Array<NotificationRecord>] {
    return [
        value[0],
        from_candid_vec_n7(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prizeCredited: null;
} | {
    scoresUpdated: null;
} | {
    tournamentStarting: null;
} | {
    registrationConfirmed: null;
}): NotificationType {
    return "prizeCredited" in value ? NotificationType.prizeCredited : "scoresUpdated" in value ? NotificationType.scoresUpdated : "tournamentStarting" in value ? NotificationType.tournamentStarting : "registrationConfirmed" in value ? NotificationType.registrationConfirmed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deposit: null;
} | {
    withdrawal: null;
} | {
    bonus: null;
} | {
    entryFee: null;
} | {
    prize: null;
}): TransactionType {
    return "deposit" in value ? TransactionType.deposit : "withdrawal" in value ? TransactionType.withdrawal : "bonus" in value ? TransactionType.bonus : "entryFee" in value ? TransactionType.entryFee : "prize" in value ? TransactionType.prize : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    player: null;
}): Variant_admin_player {
    return "admin" in value ? Variant_admin_player.admin : "player" in value ? Variant_admin_player.player : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): RegistrationStatus {
    return "pending" in value ? RegistrationStatus.pending : "approved" in value ? RegistrationStatus.approved : "rejected" in value ? RegistrationStatus.rejected : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
} | {
    ongoing: null;
}): TournamentStatus {
    return "upcoming" in value ? TournamentStatus.upcoming : "completed" in value ? TournamentStatus.completed : "ongoing" in value ? TournamentStatus.ongoing : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    battleground: null;
} | {
    custom4v4: null;
}): TournamentType {
    return "battleground" in value ? TournamentType.battleground : "custom4v4" in value ? TournamentType.custom4v4 : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositRequest>): Array<DepositRequest> {
    return value.map((x)=>from_candid_DepositRequest_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamRegistration>): Array<TeamRegistration> {
    return value.map((x)=>from_candid_TeamRegistration_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tournament>): Array<Tournament> {
    return value.map((x)=>from_candid_Tournament_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_NotificationRecord>]>): Array<[Principal, Array<NotificationRecord>]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Wallet>): Array<Wallet> {
    return value.map((x)=>from_candid_Wallet_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationRecord>): Array<NotificationRecord> {
    return value.map((x)=>from_candid_NotificationRecord_n8(_uploadFile, _downloadFile, x));
}
function to_candid_TournamentStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): _TournamentStatus {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentType): _TournamentType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Player> | null): [] | [Array<_Player>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    username: string;
    role: Variant_admin_player;
    banned: boolean;
    email: string;
}): {
    referralCode: string;
    username: string;
    role: {
        admin: null;
    } | {
        player: null;
    };
    banned: boolean;
    email: string;
} {
    return {
        referralCode: value.referralCode,
        username: value.username,
        role: to_candid_variant_n56(_uploadFile, _downloadFile, value.role),
        banned: value.banned,
        email: value.email
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentType): {
    battleground: null;
} | {
    custom4v4: null;
} {
    return value == TournamentType.battleground ? {
        battleground: null
    } : value == TournamentType.custom4v4 ? {
        custom4v4: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    deposit: null;
} | {
    withdrawal: null;
} | {
    bonus: null;
} | {
    entryFee: null;
} | {
    prize: null;
} {
    return value == TransactionType.deposit ? {
        deposit: null
    } : value == TransactionType.withdrawal ? {
        withdrawal: null
    } : value == TransactionType.bonus ? {
        bonus: null
    } : value == TransactionType.entryFee ? {
        entryFee: null
    } : value == TransactionType.prize ? {
        prize: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_admin_player): {
    admin: null;
} | {
    player: null;
} {
    return value == Variant_admin_player.admin ? {
        admin: null
    } : value == Variant_admin_player.player ? {
        player: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): {
    upcoming: null;
} | {
    completed: null;
} | {
    ongoing: null;
} {
    return value == TournamentStatus.upcoming ? {
        upcoming: null
    } : value == TournamentStatus.completed ? {
        completed: null
    } : value == TournamentStatus.ongoing ? {
        ongoing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
